server:
  port: 80

#应用配置
app:
  config:
    # 版本，方便通过接口版本升级
    api-version: v1
    #跨域
    cross-origin: '*'

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy

#Chatglm SDK Config
chatglm:
  sdk:
    config:
      #官网地址
      api-host: https://open.bigmodel.cn/
      #秘钥
      api-key: 389406a16d0ad1bbed7860f408dfe27e.oLiYZK7lobnFmzvu


# 微信公众号配置信息
# originalid：原始ID
# appid：个人AppID
# token：开通接口服务自定义设置
wx:
  config:
    originalid: gh_b286ef7fce39
    appid: wxbc57b508d086a85d
    token: b8b6

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml